# -*- coding: utf-8 -*-
"""Challenge4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GuYjZVEJU9LD20B2jvX8TdgIwAY28Mav
"""

from google.colab import files
files.upload()

import os
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d elvis23/mental-health-conversational-data

!unzip mental-health-conversational-data -d ./data

import os
import json
import random
import numpy as np
import pandas as pd

# Semantic embeddings
from sentence_transformers import SentenceTransformer, util

# Ensure reproducibility
random.seed(42)

# Load data
with open('./data/intents.json', 'r') as f:
    data = json.load(f)

data_list = []
for intent in data['intents']:
    tag = intent['tag']
    responses = intent.get('responses', [])
    for pattern in intent.get('patterns', []):
        data_list.append({'tag': tag, 'pattern': pattern, 'responses': responses})
if not data_list:
    raise ValueError("No data loaded from intents.json")

# DataFrame
df_expanded = pd.DataFrame(data_list)

# Load SentenceTransformer model
model_name = 'all-MiniLM-L6-v2'
embedder = SentenceTransformer(model_name)

# Precompute embeddings for all patterns
patterns = df_expanded['pattern'].tolist()
pattern_embeddings = embedder.encode(patterns, convert_to_tensor=True)

def predict_intent(user_input, threshold=0.6):
    # Compute embedding for user input
    user_emb = embedder.encode(user_input, convert_to_tensor=True)
    # Compute cosine similarities
    cos_scores = util.cos_sim(user_emb, pattern_embeddings)[0]
    # Find best match
    top_idx = int(np.argmax(cos_scores))
    score = float(cos_scores[top_idx])
    if score < threshold:
        return 'unknown', score
    return df_expanded.iloc[top_idx]['tag'], score


def generate_response(intent):
    if intent == 'unknown':
        return "I'm not sure I understand. Could you rephrase?"
    # Collect possible responses and choose randomly
    responses = df_expanded[df_expanded['tag'] == intent]['responses'].iloc[0]
    return random.choice(responses)

# Chat loop
if __name__ == '__main__':
    print("Start chatting with the Semantic Chatbot (type 'quit' to stop)")
    while True:
        user_input = input("You: ")
        if user_input.lower() in ['quit', 'exit']:
            print("Chatbot: Goodbye!")
            break
        intent, conf = predict_intent(user_input)
        response = generate_response(intent)
        print(f"[Intent: {intent}, Similarity: {conf:.2f}]")
        print("Chatbot:", response)

